# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37d221035bffe984d33932e6d7c3b9c7307d92d3105e8bbff68c4054aab31349f1818ff4d595f148e365bdeb377358bc8d8c6e19dc9e1d0453fc9a0cda596715

test:
  secret_key_base: 7c1600501e6319a69022c37bc2f1a5247cce3c57b5c67a4db5b1eb40f7f4bafbd26dc535f8fa6dc9b7ffaf56147fc9f90aa359f8f88376746f8cfb268fa353aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
